name = "adobe-commerce-catalog-dev"
main = "dist/index.mjs"
compatibility_date = "2024-03-21"
account_id = "852dfa4ae1b0d579df29be65b986c101"
workers_dev = true
send_metrics = false

build = { command = "npm install && node build.js" }

kv_namespaces = [
  { binding = "CONFIGS", id = "bb91e12a65a8462282396f32e63406f1", preview_id = "bb91e12a65a8462282396f32e63406f1" }
]

[vars]
VERSION = "@@VERSION@@-dev"
ENVIRONMENT = "dev"

[[r2_buckets]]
binding = "CATALOG_BUCKET"  # Access in script via env.MY_BUCKET
preview_bucket_name = "adobe-commerce-catalog-dev"
bucket_name = "adobe-commerce-catalog"

# ----------------------------------------------------------------------
# ci environment

[env.ci]
name = "adobe-commerce-catalog-ci"

kv_namespaces = [
  { binding = "CONFIGS", id = "bb91e12a65a8462282396f32e63406f1", preview_id = "bb91e12a65a8462282396f32e63406f1" }
]

[env.ci.vars]
VERSION = "@@VERSION@@-ci"
ENVIRONMENT = "ci"

# ----------------------------------------------------------------------
# production environment

[env.production]
name = "adobe-commerce-catalog"

kv_namespaces = [
  { binding = "CONFIGS", id = "bb91e12a65a8462282396f32e63406f1", preview_id = "bb91e12a65a8462282396f32e63406f1" }
]

[env.production.vars]
VERSION = "@@VERSION@@"
ENVIRONMENT = "prod"

# [secrets]
# ...